# Generated by Django 5.2 on 2025-05-07 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0002_student_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
