# Generated by Django 5.2 on 2025-05-28 19:03

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0005_alter_student_file_alter_student_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video'),
        ),
    ]
