services:
  - type: web
    name: o-quvmarkaz
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn asosiy.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: asosiy.settings
